Fix less @import compilation step
QubitProducts/jest pull request #9
Opened 2021-11-08 16:01 UTC by BenKandelaars

When running `npx jest --no-cache` in a experience related repo such as `@qubit/search-preview` throws an `TypeError: Cannot read property 'css' of undefined` error. Error is due to the ability of `less.render` to follow `@import` rules. By providing the filename less is able to resolve the relative location of the imported file and correctly append it to the rendered css. Also, there is no need to provide `sync: true` as less runs synchronously when a callback is provided.

2021-11-08 16:12 UTC, liviarett commented on package.json
> +    "@qubit/jest": "^1.4.0",
isn't this this package?

2021-11-08 17:32 UTC, alanclarke approved these changes

2021-11-08 17:33 UTC, alanclarke commented on package.json
> +    "@qubit/jest": "^1.4.0",
ah yeah need to delete this

2021-11-08 17:33 UTC, alanclarke requested changes
circular dep

2021-11-09 10:24 UTC, BenKandelaars commented
There seems to be a circular dependency bug with jest where the it isn't able to resolve @qubit/jest in the transform config. Tests do pass when @qubit/jest in installed as a dependency

2021-11-12 14:54 UTC, liviarett commented
@BenKandelaars did you see this is failing?

2021-11-22 14:22 UTC, alanclarke approved these changes

2021-11-22 16:09 UTC, merged